package com.karnataka.fabric.core.domain;

public enum AuditEventType {
    RECEIVED, TRANSLATED, DISPATCHED, CONFIRMED, FAILED, CONFLICT_DETECTED, CONFLICT_RESOLVED, RETRY_QUEUED, DLQ_PARKED, SCHEMA_DRIFT_DETECTED, NL_QUERY_EXECUTED
}
